### PR TITLE
code formatting cleanup

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1807

There are no functional changes here, just some cleanup to make the code style more consistent.

### CODE REVIEW

**Comment by whikloj** [comment]
You've got 2 files with just with formatting changes in this commit, could those be removed.

Otherwise this looks good and builds fine for me.

**Comment by ajs6f** [comment]
@whikloj , is that a joke?

**Comment by peichman-umd** [comment]
This builds fine for me. :+1:

**Comment by whikloj** [comment]
@ajs6f I was channeling my inner @awoods

**Comment by ajs6f** [comment]
Like [this](https://youtu.be/8QjrBjdb2T8?t=33)?

**Comment by whikloj** [comment]
@acoburn if I offended you in any way. I am truly sorry.

**Comment by acoburn** [comment]
@whikloj my only concern was that you clearly had not looked very closely at the PR -- there were three files with only formatting changes, not two!

**Comment by whikloj** [comment]
@acoburn perhaps I used unclear terminology. I considered the IT changes where you removed the try statements, to be the actual code changes that I was testing. Perhaps I was incorrect. Sorry about that.

**Pull request merged**
